@startuml
'https://plantuml.com/class-diagram

class ListManager {
ToDoList : Collection

AddList()
DeleteList()
SaveList()
LoadList()
}

class ToDoList {
name : String
Item : Collection

AddItem()
DeleteItem()
SortList()
SaveList()
DeleteList()
}

class Item {
desc : String
duedate : int
status : boolean

SetDesc(desc)
GetDesc()
SetDueDate(int)
GetDueDate()
SetStatus(boolean)
GetStatus()
}

ToDoList -- Item
ListManager -- ToDoList
App -- ListManager
@enduml