@startuml
'https://plantuml.com/class-diagram

class java.ListManager{
list : List<ToDoList> //masterlist
--
saveLists()
deleteLists()
loadList()
}

class java.ToDoList {
list : List<Event>
title : String
--
List(title)
..Setters/Getters..
setTitle()
getTitle()
..
saveList()
deleteList()
sortListAlphabetical()
sortListDuedate()
displayComplete()
displayIncomplete()
}

class java.Event {
desc : String
duedate : int //MMDDYYYY
completed : boolean
--
Event(String, LocalDate)
..Setters/Getters..
setDesc()
getDesc()
setDuedate()
getDuedate()
setCompleted()
getCompleted()
}

java.ToDoList "made up of" -- java.Event : >
java.ListManager "made up of" -- java.ToDoList : > calls methods from

java.ToDoListApp -- java.Controller : > calls
resources.FXMLfile .. java.Controller : < controls
java.Controller -- java.ListManager : > calls


class java.Controller{
--List Management--
New List
?Edit List
Load List
Save Lists
Delete Lists
--View--
Sort by Alphabetical
Sort by Duedate
Display Complete
Display Incomplete
Display All
--
New Event
Edit Event
Mark Complete/Incomplete
}

class java.ToDoListApp{
main()
start()
}

@enduml